# Generated by Django 5.2.7 on 2025-11-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('main', '0003_alter_track_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritealbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_albums', to='main.album'),
        ),
        migrations.AlterField(
            model_name='favoriteartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_artists', to='main.artist'),
        ),
        migrations.AlterField(
            model_name='favoritetrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_tracks', to='main.track'),
        ),
    ]
