# Generated by Django 5.2.7 on 2025-11-30 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
        ('favorites', '0002_alter_favoritealbum_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritealbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_albums', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='favoriteartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_artists', to='artists.artist'),
        ),
    ]
