# Generated by Django 5.2.7 on 2025-11-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_artist_options_alter_artistapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(null=True, upload_to='tracks/'),
        ),
    ]
