# Generated by Django 5.2.7 on 2025-11-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_track_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user___is_artist': True}, related_name='tracks', to='main.artist'),
        ),
    ]
