# Generated by Django 5.2.7 on 2025-11-30 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_track_artists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='main.artist'),
        ),
        migrations.CreateModel(
            name='TrackPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='main.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Track Play',
                'verbose_name_plural': 'Track Plays',
                'indexes': [models.Index(fields=['played_at'], name='main_trackp_played__b83538_idx'), models.Index(fields=['track', 'played_at'], name='main_trackp_track_i_422a86_idx')],
            },
        ),
    ]
