# Generated by Django 5.2.7 on 2025-11-30 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
        ('favorites', '0003_alter_favoritealbum_album_and_more'),
        ('main', '0007_migrate_data_to_new_apps'),
        ('pins', '0003_alter_pinnedalbum_album_alter_pinnedartist_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='albums.album'),
        ),
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='artistapplication',
            name='user',
        ),
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='artists.artist'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='ArtistApplication',
        ),
    ]
