# Generated by Django 5.2.7 on 2025-11-23 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_alter_track_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_albums', to='main.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinned Album',
                'verbose_name_plural': 'Pinned Albums',
                'unique_together': {('user', 'album')},
            },
        ),
        migrations.CreateModel(
            name='PinnedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_artists', to='main.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinned Artist',
                'verbose_name_plural': 'Pinned Artists',
                'unique_together': {('user', 'artist')},
            },
        ),
    ]
