# Generated by Django 5.2.7 on 2025-11-25 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
        ('playlists', '0003_alter_playlisttrack_playlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_playlists', to='playlists.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pinned Playlist',
                'verbose_name_plural': 'Pinned Playlists',
                'unique_together': {('user', 'playlist')},
            },
        ),
    ]
