# Generated by Django 5.2.7 on 2025-11-30 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
        ('pins', '0002_pinnedplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_albums', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='pinnedartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_artists', to='artists.artist'),
        ),
    ]
